// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgvfvmvtjvuylmdkjgag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndmZ2bXZ0anZ1eWxtZGtqZ2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDQzNzcsImV4cCI6MjA2NDg4MDM3N30.ma7-ObZs-iUAbyWPFlSuGICZ2KACR1ZP0DdwST9vT_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);